services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports: 
      - 5432:5432

  underscore:
    build:
      context: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000